# Generated by Django 6.0.2 on 2026-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('PARTICULIER', 'particulier'), ('PROFESSIONNEL', 'professionnel')], default='PARTICULIER'),
        ),
    ]
