# Generated by Django 6.0.2 on 2026-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0600000000', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
