# Generated by Django 6.0.2 on 2026-02-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_devis'),
    ]

    operations = [
        migrations.CreateModel(
            name='devi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERVENTION', 'intervention'), ('CHANTIER', 'chantier')], default='INTERVENTION')),
                ('date_of_visit', models.DateField()),
                ('date_of_devis_to_send', models.DateField()),
                ('status', models.CharField(choices=[('A FAIRE', 'A faire'), ('EN COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A FAIRE')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
            ],
        ),
        migrations.DeleteModel(
            name='devis',
        ),
    ]
