# Generated by Django 6.0.2 on 2026-02-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_devi_delete_devis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devi',
            new_name='devis',
        ),
    ]
