# Generated by Django 6.0.2 on 2026-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0006_rename_devi_devis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'verbose_name_plural': 'devis'},
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date_of_devis_to_send',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date_of_visit',
        ),
        migrations.AddField(
            model_name='devis',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='devis',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Devis envoyée ?'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('A FAIRE', 'A faire'), ('EN ATTENTE CLIENT', 'En attente client'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='A FAIRE'),
        ),
    ]
