# Generated by Django 6.0.2 on 2026-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0007_alter_devis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='createdDate',
            field=models.DateField(auto_now=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='comment',
            field=models.CharField(default='', max_length=1000, verbose_name='Note personnelle'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Devis envoyé ?'),
        ),
    ]
