# Generated by Django 6.0.2 on 2026-02-09 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0008_devis_createddate_alter_devis_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='excpectedSentDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date d'envoi prévue"),
        ),
    ]
