# Generated by Django 6.0.2 on 2026-02-09 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0009_devis_excpectedsentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='realSentDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date d'envoi réelle"),
        ),
    ]
