# Generated by Django 6.0.2 on 2026-02-09 09:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0010_devis_realsentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de la demande')),
                ('motif', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('INTERVENTION', 'intervention'), ('CHANTIER', 'chantier')], default='INTERVENTION')),
                ('excpectedVisitDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date prévue de la visite')),
                ('clientAvailibity', models.CharField(max_length=255)),
                ('realVisitDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date réele de la visite')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
            ],
        ),
    ]
