# Generated by Django 6.0.2 on 2026-02-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0011_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.demande'),
        ),
    ]
