# Generated by Django 6.0.2 on 2026-02-09 09:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0012_devis_demande'),
    ]

    operations = [
        migrations.CreateModel(
            name='travaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de début des travaux')),
                ('type', models.CharField(choices=[('INTERVENTION', 'intervention'), ('CHANTIER', 'chantier')], default='INTERVENTION')),
                ('terminated', models.BooleanField(default=False, verbose_name='Terminé ?')),
                ('endDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de fin des travaux')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.demande')),
                ('devis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.devis')),
            ],
            options={
                'verbose_name_plural': 'travaux',
            },
        ),
    ]
