# Generated by Django 6.0.2 on 2026-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0013_travaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0600000000', max_length=10, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_address',
            field=models.CharField(default='', max_length=255, verbose_name='Adresse postale'),
        ),
    ]
