# Generated by Django 6.0.2 on 2026-02-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0014_alter_client_firstname_alter_client_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='comment',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Note personnelle'),
        ),
    ]
