# Generated by Django 6.0.2 on 2026-02-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0015_alter_devis_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Note personnelle'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.demande'),
        ),
    ]
