# Generated by Django 5.0 on 2026-01-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
                ('date_derniere_relance', models.DateField(blank=True, null=True, verbose_name='Dernière relance')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant HT')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ATTENTE', 'En attente client'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='ENVOYE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
