# Generated by Django 4.2 on 2026-02-09 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastName', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('particulier', 'particulier'), ('professionnel', 'professionnel')], default='particulier', max_length=19)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('postal_address', models.CharField(max_length=255, verbose_name='Adresse postale')),
                ('phone', models.CharField(default='0600000000', max_length=10, verbose_name='Téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de la demande')),
                ('motif', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=22)),
                ('excpectedVisitDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date prévue de la visite')),
                ('clientAvailibity', models.CharField(max_length=255)),
                ('realVisitDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date réele de la visite')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=22)),
                ('status', models.CharField(choices=[('Refusé', 'Refusé'), ('Accepté', 'Accepté'), ('A faire', 'A faire'), ('En attente client', 'En attente client')], default='A faire', max_length=25)),
                ('excpectedSentDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date d'envoi prévue")),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Note personnelle')),
                ('sent', models.BooleanField(default=False, verbose_name='Devis envoyé ?')),
                ('createdDate', models.DateField(auto_now=True, verbose_name='Date de création')),
                ('realSentDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name="Date d'envoi réelle")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.demande')),
            ],
            options={
                'verbose_name_plural': 'devis',
            },
        ),
        migrations.CreateModel(
            name='travaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de début des travaux')),
                ('type', models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=24)),
                ('terminated', models.BooleanField(default=False, verbose_name='Terminé ?')),
                ('endDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de fin des travaux')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.client')),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.demande')),
                ('devis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoApp.devis')),
            ],
            options={
                'verbose_name_plural': 'travaux',
            },
        ),
    ]
