# Generated by Django 4.2 on 2026-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('Refusé', 'Refusé'), ('En attente client', 'En attente client'), ('Accepté', 'Accepté'), ('A faire', 'A faire')], default='A faire', max_length=25),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type',
            field=models.CharField(choices=[('chantier', 'chantier'), ('intervention', 'intervention')], default='intervention', max_length=22),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='type',
            field=models.CharField(choices=[('chantier', 'chantier'), ('intervention', 'intervention')], default='intervention', max_length=24),
        ),
    ]
