# Generated by Django 4.2 on 2026-02-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_alter_devis_status_alter_devis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('A faire', 'A faire'), ('Refusé', 'Refusé'), ('En attente client', 'En attente client'), ('Accepté', 'Accepté')], default='A faire', max_length=25),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type',
            field=models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=22),
        ),
        migrations.AlterField(
            model_name='travaux',
            name='type',
            field=models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=24),
        ),
    ]
