# Generated by Django 4.2 on 2026-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_alter_devis_status_alter_devis_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='type',
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('A faire', 'A faire'), ('En attente client', 'En attente client'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé')], default='A faire', max_length=25),
        ),
    ]
