# Generated by Django 4.2 on 2026-02-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_remove_devis_type_alter_devis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='type',
            field=models.CharField(choices=[('intervention', 'intervention'), ('chantier', 'chantier')], default='intervention', max_length=22),
        ),
    ]
