# Generated by Django 4.2 on 2026-02-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_devis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='type',
        ),
    ]
