# Generated by Django 5.0 on 2026-01-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('mcpt', models.CharField(blank=True, max_length=100, verbose_name='MC/PT')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('date_commande', models.DateField(blank=True, null=True, verbose_name='Date de commande')),
                ('date_visite_reelle', models.DateField(blank=True, null=True, verbose_name='Date visite réelle')),
                ('disponibilite_client', models.CharField(blank=True, max_length=200, verbose_name='Disponibilité client')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_TEMPS', 'Faite en temps et en heure'), ('EN_RETARD', 'Faite mais en retard'), ('PAS_REALISEE', 'Pas encore réalisée')], default='A_FAIRE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-date_commande'],
            },
        ),
    ]
