# Generated by Django 5.0 on 2026-01-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_realisation_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('statut', models.CharField(choices=[('NON_PREVUE', 'Non prévue'), ('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('PASSEE', 'Passée')], default='NON_PREVUE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='clients.client', verbose_name='Client')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='devis.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-date_realisation_prevue'],
            },
        ),
    ]
